version: "3.9"

services:
  debian:
    image: hkdigital/debian-slim   # docker-hub
    # image: hkdigital-debian-slim   # local

    restart: "no" # "no"|always|on-failure|unless-stopped

    env_file:
      - docker-compose.env

    volumes:
      - ./volumes/shared:/mnt/shared